Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdajectionVersion:
    Type: String
    Description: ARN of the Lambda Layer containing Lambdajection + its dependencies.

  DotnetVersion:
    Type: String
    Description: ARN of the Lambda Layer containing .NET.

  IdentityServerUri:
    Type: String
    Description: URI of the identity server.

  IdentityClientId:
    Type: String
    Description: Client ID of the Discord Application.

  IdentityClientSecret:
    Type: String
    Description: Encrypted Client Secret of the Discord Application.

  CommandsServiceUri:
    Type: String
    Description: URI of the commands service.

Resources:
  CommandResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Brighid.Commands.Resources.Command::Brighid.Commands.Resources.CommandHandler::Run
      Runtime: provided.al2
      Timeout: 30
      CodeUri: ../bin/Resources.Command/Release/linux-x64/publish/
      MemorySize: 512
      Policies:
        - !ImportValue cfn-utilities:SecretsKeyDecryptPolicyArn
      Layers:
        - !Sub "{{resolve:ssm:/dotnet/${DotnetVersion}/layer-arn}}"
        - !Sub "{{resolve:ssm:/lambdajection/${LambdajectionVersion}/layer-arn}}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue cfn-utilities:LambdaSecurityGroupId
        SubnetIds: !Split [",", !ImportValue cfn-utilities:SubnetIds]
      Environment:
        Variables:
          Identity__IdentityServerUri: !Ref IdentityServerUri
          Identity__ClientId: !Ref IdentityClientId
          Identity__ClientSecret: !Ref IdentityClientSecret
          Commands__ServiceUri: !Ref CommandsServiceUri

  CommandResourceArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /brighid/commands/resources/command/resource-arn
      Type: String
      Value: !GetAtt CommandResource.Arn
